### PR TITLE
merge_duplicate_nodes speed-up

### PR DESCRIPTION
**Pull request by maderero**
Current method iterates through all elements (members/springs/plates/quads) on every pass comparing nodes. 

In this pr, node usage is checked ahead of time to reduce runtime.
Tested with 50000 nodes and 200 elements and noted a substantially reduction in runtime (~45 sec to ~8 sec on my machine).
Also added a new method to the Node3D class (`Node3d.distance`) to calculate the distance to a secondary node.

### CODE REVIEW

**Comment by maderero** [comment]
Looks like checks are failing due to walrus operators. I'll rewrite those bits after lunch.

**Comment by JWock82** [comment]
From the checks above it looks like some of the syntax is not compatible with python 3.6 and 3.7. I'm trying to keep PyNite compatible with python 3.6+. Could you expand the details, take a look, and revise your pull request?

**Comment by maderero** [comment]
Alright I'll keep that in mind in the future. Fixed the issue!

**Comment by maderero** [comment]
Deleted branch on accident

**Pull request merged**
